### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by langjoh** [Powerglove/Thinkerinnen#30]

**Comment by jbrunton** [comment]
Here's my suggested plan of attack, with a few things to keep in mind:
1. Start by adding the Rolify gem. That's pretty easy to install, and you can test in the rails console that you can do `thinker.add_role(:admin)` and `thinker.has_role?(:admin)`.
2. Next, add the Pundit gem.
3. Add a ThinkerPolicy class (which might inherit from ApplicationPolicy). Implement a `destroy?` method which checks whether the user is an admin.
4. Add code to the destroy action in ThinkersController to authorize the user. Test that an unauthorized user will see an error if they try to destroy a thinker, but that a user with an :admin role can destroy one.
5. Improve the messaging for users who aren't authorized. See https://github.com/elabs/pundit#rescuing-a-denied-authorization-in-rails.
6. It's good practice to ensure every controller action requires authorization, so you don't forget to add it. See https://github.com/elabs/pundit#ensuring-policies-and-scopes-are-used for how to do this.
